# Site settings
title: Vaibhav Bhandari Homepage
author: Vaibhav Bhandari
email: vaibhavb@gmail.com
description: Vaibhav Bhandari Homepage
baseurl: ""
images: "/assets/images"
url: "https://www.vitraag.com"

#Exclude
exclude: [data-runners, vendor, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules/*, assets/webpack, _includes/notes_graph.json]
include: [_pages, _kamals_kitchen]

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
safe: false

collections:
  notes:
    output: true
    permalink: /notes/:slug/
  newsletters:
    output: true
    permalink: /newsletter/:name/
    sort_by: date

defaults:
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_newsletters"
      type: "newsletters"
    values:
      layout: "newsletter"
      rss_eligible: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
